# Kubernetes deployment description for Identifiers.org Resource Recommender Web Service
#
# Author: Manuel Bernal Llinares <mbdebian@gmail.com>
apiVersion: apps/v1beta2
kind: Deployment
metadata:
    name: resource-recommender
spec:
    selector:
        matchLabels:
            environment: production
            tier: api
            app: resource-recommender
    replicas: 1
    template:
        metadata:
            labels:
                environment: production
                tier: api
                app: resource-recommender
        spec:
            containers:
                - name: cloud-ws-resource-recommender
                  image: identifiersorg/cloud-ws-resource-recommender:1.1.0
                  imagePullPolicy: Always
                  resources:
                      requests:
                          memory: 640Mi
                  env:
                  - name: WS_RESOURCE_RECOMMENDER_JVM_MEMORY_MAX
                    value: "512m"
                  - name: WS_RESOURCE_RECOMMENDER_CONFIG_BACKEND_SERVICE_LINK_CHECKER_HOST
                    value: link-checker
                  ports:
                  - containerPort: 8083
