# Kubernetes deployment description for Identifiers.org Prefix Registration API Service
# Author: Manuel Bernal Llinares <mbdebian@gmail.com>
apiVersion: apps/v1
kind: Deployment
metadata:
    name: registry
spec:
    selector:
        matchLabels:
            environment: production
            tier: api
            app: registry
    replicas: 2
    template:
        metadata:
            labels:
                environment: production
                tier: api
                app: registry
        spec:
            containers:
                - name: cloud-ws-registry
                  image: identifiersorg/cloud-ws-registry:1.1.0
                  imagePullPolicy: Always
                  resources:
                      requests:
                          memory: 640Mi
                  env:
                  - name: WS_REGISTRY_CONFIG_REDIS_HOST
                    value: "redis"
                  - name: WS_REGISTRY_CONFIG_REDIS_PORT
                    value: "6379"
                  - name: WS_REGISTRY_CONFIG_RESOLVER_HOST
                    value: "resolver"
                  - name: WS_REGISTRY_CONFIG_RESOLVER_PORT
                    value: "8080"
                  - name: WS_REGISTRY_CONFIG_EMAIL_HOST
                    value: "email-smtp.us-east-1.amazonaws.com"
                  - name: WS_REGISTRY_CONFIG_EMAIL_PORT
                    value: "587"
                  - name: WS_REGISTRY_CONFIG_EMAIL_FROM
                    value: "identifiers.org@gmail.com"
                  - name: WS_REGISTRY_CONFIG_EMAIL_USERNAME
                    valueFrom:
                        secretKeyRef:
                            name: aws-smtp-credentials
                            key: username
                  - name: WS_REGISTRY_CONFIG_EMAIL_PASSWORD
                    valueFrom:
                        secretKeyRef:
                            name: aws-smtp-credentials
                            key: password
                  - name: WS_REGISTRY_CONFIG_EMAIL_TRANSPORT_PROTOCOL
                    value: "smtp"
                  - name: WS_REGISTRY_CONFIG_EMAIL_BOOLEAN_SMTP_AUTH
                    value: "true"
                  - name: WS_REGISTRY_CONFIG_EMAIL_BOOLEAN_START_TLS
                    value: "true"
                  - name: WS_REGISTRY_CONFIG_EMAIL_BOOLEAN_DEBUG
                    value: "true"
                  - name: WS_REGISTRY_JVM_MEMORY_MAX
                    value: "512m"
                  ports:
                  - containerPort: 8081
